### ISSUE TITLE
Import features from exisiting Entities

### ISSUE THREAD

**Issue by javydreamercsw** [jeddict/jeddict#188]
The following are not imported on the model when creating from Entities:

- Existing Named Queries

- Existing hashCode/equals

- Existing toString method

- ID Generator (i.e. TableGenerator)

It's just unmanageable to recreate all this in the imported model.

**Comment by jGauravGupta** [comment]
Hi @javydreamercsw ,

Java Class Reverse engineering is not supported for hashCode/equals/toString/constructor , custom method/property/annotation/snippet/comments/javadoc.

With the DB reverse engineering , you can not recover embeddable , mapped super class , converter etc.

For Named Queries and ID Generator , I tried and it is working fine , so can you attach sample java entity to reproduce the issue for Named Queries and ID Generator reverse engineering.

**Comment by javydreamercsw** [comment]
- I'm aware it is not supported, is a request for that. Additional methods have no reason to be removed during the import. Same with additional constructors, comments, etc. All my requests were for Java Class Reverse engeneering.

- This is an example of entity with annotations and id that didn't get imported. Created with NetBeans wizards. [AssigmentType.pdf](https://github.com/jeddict/jeddict/files/883834/AssigmentType.pdf)

**Comment by javydreamercsw** [comment]
Otherwise the Java Class Reverse engineering feature is kind of non-existent if you have to convert all those into modeler format. Works well if you start from database or a new diagram.

If it is expected for this to be broadly accepted by existing users it needs to provide this support or it'll be dropped really fast.

**Comment by javydreamercsw** [comment]
If you point me to the piece of code that does the importing I might take a look and help if not too involved.

**Comment by javydreamercsw** [comment]
I would probably try something like [this](http://javaparser.org/index.html) to parse methods, etc. and act upon it.

**Comment by jGauravGupta** [comment]
Great , Please find the following link for Java Class reverse engineering snippet.

 Java Class reverse engineering snippet:
https://github.com/jeddict/jCode/blob/master/JPA%20Specification/src/org/netbeans/jpa/modeler/spec/extend/JavaClass.java#L117

Root Call:
https://github.com/jeddict/jeddict/blob/master/JPA%20Classes%20Reverse%20Engineering/src/org/netbeans/jpa/modeler/jcre/wizard/JPAModelGenerator.java#L51

Clas Hierarchy : 
```
	at org.netbeans.jpa.modeler.spec.extend.JavaClass.load(JavaClass.java:120)
	at org.netbeans.jpa.modeler.spec.ManagedClass.load(ManagedClass.java:34)
	at org.netbeans.jpa.modeler.spec.IdentifiableClass.load(IdentifiableClass.java:94)
	at org.netbeans.jpa.modeler.spec.Entity.load(Entity.java:186)
	at org.netbeans.jpa.modeler.jcre.wizard.JPAModelGenerator$1.run(JPAModelGenerator.java:51)
	at org.netbeans.jpa.modeler.jcre.wizard.JPAModelGenerator$1.run(JPAModelGenerator.java:41)
	....
	at org.netbeans.jpa.modeler.jcre.wizard.JPAModelGenerator.generateJPAModel(JPAModelGenerator.java:41)
	at org.netbeans.jpa.modeler.jcre.wizard.RevEngWizardDescriptor.generateJPAModel(RevEngWizardDescriptor.java:196)
	at org.netbeans.jpa.modeler.jcre.wizard.RevEngWizardDescriptor.lambda$instantiateJCREProcess$0(RevEngWizardDescriptor.java:125)
	at org.netbeans.jpa.modeler.jcre.wizard.RevEngWizardDescriptor$$Lambda$130.18955681.run
```

Call intiated from **JPA Classes Reverse Engineering** project and reverse engineering is passed to domain object available in **JPA Specification** project.

**Comment by javydreamercsw** [comment]
Forked and looking into it.

**Comment by jGauravGupta** [comment]
https://github.com/jeddict/NBModeler is also required to setup.

**Comment by javydreamercsw** [comment]
Had to learn the hard way that to even compile the code you need the following:

1. Need to work on NetBeans 8.2.

1. Need to have Jeddict installed.

Probably need to set up instructions on how to contribute ;)

**Comment by jGauravGupta** [comment]
Please check : https://jeddict.github.io/page.html?l=tutorial/Contribute
This doc helps to create custom code generator but may be it will help you to setup code.

**Comment by javydreamercsw** [comment]
Getting error when compiling jeddict:
```
/home/javier/NetBeansProjects/jeddict/JPA Modeler/src/org/netbeans/jpa/modeler/specification/model/scene/JPAModelerScene.java:95: error: JPAModelerScene is not abstract and does not override abstract method createTreeView() in IModelerScene
public class JPAModelerScene extends DefaultPModelerScene<EntityMappings> {
Note: Some input files additionally use or override a deprecated API.
Note: Some input files additionally use unchecked or unsafe operations.
1 error
```
Any idea?

**Comment by jGauravGupta** [comment]
Take the latest src again of NBModeler and Jeddict

**Comment by javydreamercsw** [comment]
I did everything on that tutorial already, but having the error above compiling/running jeddict.

**Comment by jGauravGupta** [comment]
There was conflict(api not-sync) between commit of two different project , please take the latest src again of NBModeler and Jeddict.

**Comment by javydreamercsw** [comment]
I thought it was something like that.

Had to stop for the day. Will take a look next week.

If it wasn't for that issue I could have had some good quality time with the code.

**Comment by javydreamercsw** [comment]
Sadly it seems way more convoluted than expected. I don't have the time to commit to contribute.

**Comment by jGauravGupta** [comment]
Fixed by commit : 720eea447108ef912a3859fc4e167411ea55c71e
Duplicate ticket : #275
